// Mock data for Bumbull dating app
// This will be replaced with actual API calls when backend is ready

export const mockUsers = [
  {
    id: 1,
    first_name: "Sarah",
    last_name: "Johnson",
    phone_number: "+989123456789",
    gender: "F",
    date_of_birth: "1998-05-15",
    biography: "Adventure seeker & coffee lover ☕ Looking for someone to explore the world with. Love hiking, photography, and late-night conversations.",
    height_cm: 168,
    fun_question: "If you could have dinner with anyone, who would it be?",
    fun_answer: "Anthony Bourdain — for the food AND the stories",
    city_birth: "tehran",
    city_lives: "tehran",
    latitude: 35.6892,
    longitude: 51.3890,
    interests: [
      { id: 1, name: "Photography", slug: "photography" },
      { id: 2, name: "Hiking", slug: "hiking" },
      { id: 5, name: "Coffee", slug: "coffee" },
      { id: 8, name: "Travel", slug: "travel" },
    ],
    membership: "gold",
    membership_expiry: "2026-12-01T00:00:00Z",
    invite_code: "SAR4H1",
    is_phone_verified: true,
    photos: [
      { id: 1, order: 0, is_primary: true, image: "/mock/users/sarah_1.jpg" },
      { id: 2, order: 1, is_primary: false, image: "/mock/users/sarah_2.jpg" },
      { id: 3, order: 2, is_primary: false, image: "/mock/users/sarah_3.jpg" },
    ],
    age: 28,
  },
  {
    id: 2,
    first_name: "Emma",
    last_name: "Wilson",
    phone_number: "+989123456780",
    gender: "F",
    date_of_birth: "2000-11-22",
    biography: "Music is my therapy 🎵 Yoga enthusiast. Believe in good vibes and great playlists. Let's share headphones?",
    height_cm: 165,
    fun_question: "What's your go-to karaoke song?",
    fun_answer: "Bohemian Rhapsody — full performance, no shortcuts",
    city_birth: "isfahan",
    city_lives: "tehran",
    latitude: 35.7219,
    longitude: 51.3347,
    interests: [
      { id: 3, name: "Music", slug: "music" },
      { id: 4, name: "Yoga", slug: "yoga" },
      { id: 6, name: "Art", slug: "art" },
      { id: 9, name: "Cooking", slug: "cooking" },
    ],
    membership: "silver",
    membership_expiry: "2026-09-15T00:00:00Z",
    invite_code: "EMM4W2",
    is_phone_verified: true,
    photos: [
      { id: 4, order: 0, is_primary: true, image: "/mock/users/emma_1.jpg" },
      { id: 5, order: 1, is_primary: false, image: "/mock/users/emma_2.jpg" },
      { id: 6, order: 2, is_primary: false, image: "/mock/users/emma_3.jpg" },
    ],
    age: 25,
  },
  {
    id: 3,
    first_name: "Sophia",
    last_name: "Martinez",
    phone_number: "+989123456781",
    gender: "F",
    date_of_birth: "1999-03-08",
    biography: "Bookworm with a passion for architecture 📚🏛️ Tell me about your favorite building and I'll tell you mine.",
    height_cm: 170,
    fun_question: "Window seat or aisle seat?",
    fun_answer: "Window — I need to see the clouds",
    city_birth: "shiraz",
    city_lives: "isfahan",
    latitude: 32.6546,
    longitude: 51.6680,
    interests: [
      { id: 7, name: "Reading", slug: "reading" },
      { id: 6, name: "Art", slug: "art" },
      { id: 8, name: "Travel", slug: "travel" },
      { id: 10, name: "Architecture", slug: "architecture" },
    ],
    membership: "bronze",
    membership_expiry: null,
    invite_code: "SOPH33",
    is_phone_verified: true,
    photos: [
      { id: 7, order: 0, is_primary: true, image: "/mock/users/sophia_1.jpg" },
      { id: 8, order: 1, is_primary: false, image: "/mock/users/sophia_2.jpg" },
      { id: 9, order: 2, is_primary: false, image: "/mock/users/sophia_3.jpg" },
    ],
    age: 27,
  },
  {
    id: 4,
    first_name: "Olivia",
    last_name: "Chen",
    phone_number: "+989123456782",
    gender: "F",
    date_of_birth: "1997-07-19",
    biography: "Tech geek who also loves to paint 🎨💻 Building apps by day, watercolors by night. Looking for my debugging partner.",
    height_cm: 163,
    fun_question: "Tabs or spaces?",
    fun_answer: "Tabs — I like living on the edge",
    city_birth: "tehran",
    city_lives: "tehran",
    latitude: 35.7000,
    longitude: 51.4100,
    interests: [
      { id: 11, name: "Technology", slug: "technology" },
      { id: 6, name: "Art", slug: "art" },
      { id: 9, name: "Cooking", slug: "cooking" },
      { id: 12, name: "Gaming", slug: "gaming" },
    ],
    membership: "gold",
    membership_expiry: "2027-01-20T00:00:00Z",
    invite_code: "OLV4CH",
    is_phone_verified: true,
    photos: [
      { id: 10, order: 0, is_primary: true, image: "/mock/users/olivia_1.jpg" },
      { id: 11, order: 1, is_primary: false, image: "/mock/users/olivia_2.jpg" },
      { id: 12, order: 2, is_primary: false, image: "/mock/users/olivia_3.jpg" },
    ],
    age: 29,
  },
  {
    id: 5,
    first_name: "Mia",
    last_name: "Roberts",
    phone_number: "+989123456783",
    gender: "F",
    date_of_birth: "2001-01-30",
    biography: "Fitness junkie & smoothie connoisseur 💪🥤 Catch me at sunrise yoga or sunset runs. Life's too short for bad vibes.",
    height_cm: 172,
    fun_question: "Morning person or night owl?",
    fun_answer: "Both — I'm just always awake apparently",
    city_birth: "gorgan",
    city_lives: "tehran",
    latitude: 35.6750,
    longitude: 51.4200,
    interests: [
      { id: 13, name: "Fitness", slug: "fitness" },
      { id: 4, name: "Yoga", slug: "yoga" },
      { id: 14, name: "Running", slug: "running" },
      { id: 5, name: "Coffee", slug: "coffee" },
    ],
    membership: "silver",
    membership_expiry: "2026-10-05T00:00:00Z",
    invite_code: "MIA5RB",
    is_phone_verified: true,
    photos: [
      { id: 13, order: 0, is_primary: true, image: "/mock/users/mia_1.jpg" },
      { id: 14, order: 1, is_primary: false, image: "/mock/users/mia_2.jpg" },
      { id: 15, order: 2, is_primary: false, image: "/mock/users/mia_3.jpg" },
    ],
    age: 25,
  },
];

export const mockCurrentUser = {
  id: 100,
  first_name: "Alex",
  last_name: "Thompson",
  phone_number: "+989121234567",
  gender: "M",
  date_of_birth: "1998-09-12",
  biography: "Software developer by day, guitarist by night 🎸 Always up for a good debate about the best pizza toppings.",
  height_cm: 182,
  fun_question: "What's the most spontaneous thing you've done?",
  fun_answer: "Booked a one-way ticket to Tokyo at 2am",
  city_birth: "tehran",
  city_lives: "tehran",
  latitude: 35.6892,
  longitude: 51.3890,
  interests: [
    { id: 3, name: "Music", slug: "music" },
    { id: 11, name: "Technology", slug: "technology" },
    { id: 8, name: "Travel", slug: "travel" },
    { id: 5, name: "Coffee", slug: "coffee" },
    { id: 12, name: "Gaming", slug: "gaming" },
  ],
  membership: "gold",
  membership_expiry: "2027-03-01T00:00:00Z",
  invite_code: "ALEX01",
  is_phone_verified: true,
  photos: [
    { id: 100, order: 0, is_primary: true, image: "/mock/users/alex_1.jpg" },
    { id: 101, order: 1, is_primary: false, image: "/mock/users/alex_2.jpg" },
    { id: 102, order: 2, is_primary: false, image: "/mock/users/alex_3.jpg" },
  ],
  age: 27,
  swipe_quota: {
    likes_today: 12,
    super_likes_today: 0,
    max_likes: 999,
    max_super_likes: 5,
  },
};

export const mockMatches = [
  {
    id: 1,
    user1: 100,
    user2: 1,
    created_at: "2026-06-15T14:30:00Z",
    partner: mockUsers[0],
  },
  {
    id: 2,
    user1: 2,
    user2: 100,
    created_at: "2026-06-14T09:15:00Z",
    partner: mockUsers[1],
  },
  {
    id: 3,
    user1: 100,
    user2: 3,
    created_at: "2026-06-10T18:45:00Z",
    partner: mockUsers[2],
  },
];

export const mockInterests = [
  { id: 1, name: "Photography", slug: "photography" },
  { id: 2, name: "Hiking", slug: "hiking" },
  { id: 3, name: "Music", slug: "music" },
  { id: 4, name: "Yoga", slug: "yoga" },
  { id: 5, name: "Coffee", slug: "coffee" },
  { id: 6, name: "Art", slug: "art" },
  { id: 7, name: "Reading", slug: "reading" },
  { id: 8, name: "Travel", slug: "travel" },
  { id: 9, name: "Cooking", slug: "cooking" },
  { id: 10, name: "Architecture", slug: "architecture" },
  { id: 11, name: "Technology", slug: "technology" },
  { id: 12, name: "Gaming", slug: "gaming" },
  { id: 13, name: "Fitness", slug: "fitness" },
  { id: 14, name: "Running", slug: "running" },
  { id: 15, name: "Dancing", slug: "dancing" },
  { id: 16, name: "Movies", slug: "movies" },
  { id: 17, name: "Nature", slug: "nature" },
  { id: 18, name: "Fashion", slug: "fashion" },
  { id: 19, name: "Meditation", slug: "meditation" },
  { id: 20, name: "Volunteering", slug: "volunteering" },
];

export const cityChoices = [
  { value: "tehran", label: "Tehran" },
  { value: "isfahan", label: "Isfahan" },
  { value: "shiraz", label: "Shiraz" },
  { value: "gorgan", label: "Gorgan" },
];

export const genderChoices = [
  { value: "M", label: "Male" },
  { value: "F", label: "Female" },
];

export const membershipTiers = {
  bronze: {
    name: "Bronze",
    color: "#CD7F32",
    dailyLikes: 50,
    dailySuperLikes: 1,
    features: ["50 Likes per day", "1 Super Like per day", "Basic profile"],
  },
  silver: {
    name: "Silver",
    color: "#C0C0C0",
    dailyLikes: 150,
    dailySuperLikes: 3,
    features: ["150 Likes per day", "3 Super Likes per day", "Priority matching", "See who liked you"],
  },
  gold: {
    name: "Gold",
    color: "#FFD700",
    dailyLikes: 999,
    dailySuperLikes: 5,
    features: ["Unlimited Likes", "5 Super Likes per day", "Priority matching", "See who liked you", "Boost your profile", "No ads"],
  },
};
